anantha/account/urls.py
from django.urls import path
from . import views as v

app_name = 'accounts'
urlpatterns = [
    path('register',v.register,name='register'),
    path('login/',v.loginpage,name='login'),
    path('logout',v.logoutpage,name='logout'),
    
]

anantha/anantha/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('',include('account.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

anantha/base/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views as v

app_name = 'base'
urlpatterns = [
    path('',v.index,name='index'),
    path('contact',v.contact,name='contact'),
    path('mycart',v.mycart,name='mycart'),
    path('items',v.items,name='items'),
    path('update',v.update,name='update'),
    path('update/<int:pk>/',v.update_dress,name='update-dress'),
    path('add-dress',v.adddress,name='add-dress'),
    path('ipage/<int:pk>/',v.ipage,name='ipage'),
    path('remove_from_cart/<int:item_id>/', v.remove_from_cart, name='remove_from_cart'),
    path('order_confirmation', v.order_confirmation, name='order_confirmation'),
    path('checkout/', v.checkout, name='checkout'),
]

anantha/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Anantya</title>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/main.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">

</head>
<body>
    {% include 'nav.html'%}
    {% block body %}
    {% endblock %}
</body>
</html>

anantha/templates/nav.html
{% load static %}

<nav class="navbar">
    <div class="nav-container">
        <a href="{% url 'base:index' %}" class="logo">
            <img src="{% static 'styles/logo.jpg' %}" alt="Logo" />
        </a>
        <h1 class="nav-title" style="font-family: 'Times New Roman', Times, serif;">ANANTYA</h1>
        <ul class="nav-links">
            <li><a href="#categories">Categories</a></li>
            {% if user.is_authenticated and user.userprofile.post == "admin" %}
            <li><a href="{% url 'base:update' %}">Update</a></li>
            {% else %}
                <li> <a href="{% url 'base:mycart' %}">Mycart</a></li>
            {% endif %}
            <li><a href="{% url 'base:contact' %}">Contact</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            {% endif %}

        </ul>
    </div>
</nav>